# Site settings
url: "https://theaifactory.github.io"
baseurl: ""
brief-intro: Now leave AI to AIFactory.
email: tykim@aifactory.page
description: Machine Learning Social Media
title: AIFactory
permalink: /:year/:month/:day/:title/
timezone: Etc/UTC

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# post future
future: true

# comment
disqus: tykimos

# pagination
category_dir: publisher/
tag_dir: tag/
plugins: [jekyll-paginate]
paginate: 10
